### ISSUE TITLE
Trim armor doesn't display on item frame

### ISSUE THREAD

**Issue by SkyWors** [MincraftEinstein/ArmorTrimItemFix#1]
Hey, great mod!

For some reason, a trim armor doesn't display on item frame.

![image](https://github.com/MincraftEinstein/ArmorTrimItemFix/assets/70440695/bcd611f0-1460-4a68-b584-bff2babe661d)

**Comment by MincraftEinstein** [comment]
Hi.
I loaded up the game in Fabric and Forge and found no issue, so I am guessing it is an incompatibility with another mod. If you know what mod or have any mods you think are causing it then please let me know. If not then please send me a list of the mods you have installed so I can look through them

**Comment by MincraftEinstein** [comment]
Hi, thanks for letting me know
