### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Nuttar2004** [MincraftEinstein/ArmorTrimItemFix#2]
Hello, I am a player from China. I really like your mod and hope it will be known by more Chinese players. Can I ask you if you allow me to carry the download links of CurseForge and Modrinth of this Mod to: https://www.mcmod.cn/
 I will not issue a direct download method for this Mod on this website, I will only provide some links to your post, and Chinese players still need to go to your post to download your Mod.

**Comment by MincraftEinstein** [comment]
Hi. Thank you for asking! Yes, I will let you repost the mod to McMod for Chinese players to use, but you'll need to do what you say and not provide direct downloads and instead provide links to the original posts. Also please send me a link to your post when it's done.

**Comment by x-yingcan-x** [comment]
Already done( I did nothing, just send the link XD). https://www.mcmod.cn/class/11565.html
You may not be able to connect because of region. (If you can, ignore this)
