### ISSUE TITLE
Mod does not work?

### ISSUE THREAD

**Issue by h9lis** [MincraftEinstein/ArmorTrimItemFix#7]
![image](https://github.com/MincraftEinstein/ArmorTrimItemFix/assets/166412570/6a838806-547d-4e52-a014-fbe4d8573f24)
![image](https://github.com/MincraftEinstein/ArmorTrimItemFix/assets/166412570/702785f0-648f-4bb5-ae00-4c272459427a)
 
![image](https://github.com/MincraftEinstein/ArmorTrimItemFix/assets/166412570/7ace014a-acb9-4769-82ed-88f442edc74f)

**Comment by MincraftEinstein** [comment]
it looks like it should work. maybe try switching the fabric and vanilla resource packs, unless you did that to try to fix it, otherwise can you please send the log file?

**Comment by h9lis** [comment]
oh, it fixed the problem, ty
